name: Build Notebook Container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish to Binder
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_REGISTRY: ghcr.io
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        MYBINDERORG_CACHE: true
